[[permission]]
identifier = "crawler"
description = "Crawler window permissions"
commands.allow = [
    # apis
    "crawl_get_page_label",
    "crawl_get_page_state",
    "crawl_get_state",
    "crawl_task_log",
    "crawl_add_progress",
    "crawl_download_image",
    "crawl_media_begin",
    "crawl_media_chunk",
    "crawl_media_end",
    "crawl_to",
    "crawl_back",
    "crawl_update_page_state",
    "crawl_update_state",
    "crawl_exit",
    "crawl_error",
    "show_crawler_window",
    "crawl_clear_site_data",
]
