[[permission]]
identifier = "surf"
description = "Surf allowed commands"
commands.allow = [
    "surf_open_devtools",
    "surf_go_back",
    "surf_go_forward",
    "surf_reload",
    "surf_navigate",
    "surf_report_url",
    "surf_download_image",
    "surf_import_media",
    "crawl_fs_get_root",
    "crawl_fs_mkdir",
    "crawl_fs_create",
    "crawl_fs_fwrite",
    "crawl_fs_close",
    "crawl_fs_remove",
    "crawl_fs_read_dir",
    "crawl_archive_zip",
    "crawl_archive_tar",
    "crawl_archive_7z",
    "crawl_ffmpeg_mux",
    "crawl_ffmpeg_probe",
]
