// Commands 模块
pub mod album;
#[cfg(not(target_os = "android"))]
pub mod crawler;
pub mod filesystem;
pub mod image;
pub mod misc;
pub mod plugin;
pub mod settings;
#[cfg(not(target_os = "android"))]
pub mod surf;
pub mod task;
pub mod wallpaper;
#[cfg(target_os = "windows")]
pub mod wallpaper_engine;
pub mod window;

pub use album::*;
#[cfg(not(target_os = "android"))]
pub use crawler::*;
pub use filesystem::*;
pub use image::*;
pub use misc::*;
pub use plugin::*;
pub use settings::*;
#[cfg(not(target_os = "android"))]
pub use surf::*;
pub use task::*;
pub use wallpaper::*;
#[cfg(target_os = "windows")]
pub use wallpaper_engine::*;
pub use window::*;
