import '@kabegame/element-plus/components/base/style'
import '@kabegame/element-plus/components/tag/style'
import '@kabegame/element-plus/components/option/style'
import '@kabegame/element-plus/components/option-group/style'
import '@kabegame/element-plus/components/scrollbar/style'
import '@kabegame/element-plus/components/popper/style'
import '@kabegame/element-plus/theme-chalk/src/select.scss'
