use super::{pascal_case, CodegenModel, Edge, EdgeKind, EdgeTarget};
use std::fmt::{self, Write};

const RUNTIME: &str = include_str!("runtime.ts");

pub(super) fn emit(model: &CodegenModel) -> String {
    let mut writer = IndentWriter::new();
    writer.line(format_args!(
        "// AUTO-GENERATED by `kabegame-cli pathql generate` — DO NOT EDIT."
    ));
    writer.line(format_args!("// Target: TypeScript"));
    writer.line(format_args!(""));
    writer.raw(RUNTIME.trim_end());
    writer.line(format_args!(""));
    writer.line(format_args!(""));

    for provider in &model.providers {
        writer.line(format_args!("// DSL provider: {}", provider.fqn));
        writer.line(format_args!(
            "class {} extends NodeBase {{",
            provider.type_name
        ));
        writer.indented(|writer| {
            for (index, edge) in provider.edges.iter().enumerate() {
                if index > 0 {
                    writer.line(format_args!(""));
                }
                emit_edge(writer, edge);
            }
        });
        writer.line(format_args!("}}"));
        writer.line(format_args!(""));
    }

    for placeholder in &model.placeholders {
        writer.line(format_args!("// {}", placeholder.source));
        writer.line(format_args!(
            "type {} = AnyProviderNode;",
            placeholder.type_name
        ));
        writer.line(format_args!(""));
    }

    writer.line(format_args!("export const pql = {{"));
    writer.indented(|writer| {
        for scheme in &model.schemes {
            let property = if is_identifier(&scheme.scheme) && !scheme.scheme.starts_with('$') {
                scheme.scheme.clone()
            } else {
                ts_string_literal(&scheme.scheme)
            };
            let root = ts_string_literal(&format!("{}://", scheme.scheme));
            if scheme.target.concrete {
                writer.line(format_args!(
                    "{}: new {}([{}]),",
                    property, scheme.target.type_name, root
                ));
            } else {
                writer.line(format_args!(
                    "{}: makeAnyProviderNode([{}]) as {},",
                    property, root, scheme.target.type_name
                ));
            }
        }
    });
    writer.line(format_args!("}} as const;"));
    writer.finish()
}

fn emit_edge(writer: &mut IndentWriter, edge: &Edge) {
    match &edge.kind {
        EdgeKind::Static { key } => {
            let property = if is_identifier(key) && !key.starts_with('$') {
                key.clone()
            } else {
                format!("[{}]", ts_string_literal(key))
            };
            writer.line(format_args!(
                "get {}(): {} {{",
                property, edge.target.type_name
            ));
            let segment = ts_string_literal(key);
            writer.indented(|writer| emit_return(writer, &segment, &edge.target));
            writer.line(format_args!("}}"));
        }
        EdgeKind::Resolve { alias } => {
            let method = format!("$resolve{}", pascal_case(alias));
            writer.line(format_args!(
                "{}(seg: string): {} {{",
                method, edge.target.type_name
            ));
            writer.indented(|writer| emit_return(writer, "seg", &edge.target));
            writer.line(format_args!("}}"));
        }
        EdgeKind::Dynamic { alias } => {
            let method = alias
                .as_ref()
                .map(|alias| format!("$child{}", pascal_case(alias)))
                .unwrap_or_else(|| "$child".to_string());
            writer.line(format_args!(
                "{}(name: string): {} {{",
                method, edge.target.type_name
            ));
            writer.indented(|writer| emit_return(writer, "name", &edge.target));
            writer.line(format_args!("}}"));
        }
    }
}

fn emit_return(writer: &mut IndentWriter, expression: &str, target: &EdgeTarget) {
    if target.concrete {
        writer.line(format_args!(
            "return this._seg({}, {});",
            expression, target.type_name
        ));
    } else {
        writer.line(format_args!("return this._anySeg({});", expression));
    }
}

fn ts_string_literal(value: &str) -> String {
    let mut output = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            '\u{08}' => output.push_str("\\b"),
            '\u{0C}' => output.push_str("\\f"),
            '\u{2028}' => output.push_str("\\u2028"),
            '\u{2029}' => output.push_str("\\u2029"),
            ch if ch.is_control() => {
                write!(output, "\\u{:04x}", ch as u32).expect("writing to String cannot fail");
            }
            ch => output.push(ch),
        }
    }
    output.push('\"');
    output
}

fn is_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    matches!(chars.next(), Some('a'..='z' | 'A'..='Z' | '_' | '$'))
        && chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '$')
}

struct IndentWriter {
    output: String,
    indent: usize,
}

impl IndentWriter {
    fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
        }
    }

    fn raw(&mut self, value: &str) {
        self.output.push_str(value);
    }

    fn line(&mut self, args: fmt::Arguments<'_>) {
        for _ in 0..self.indent {
            self.output.push_str("  ");
        }
        self.output
            .write_fmt(args)
            .expect("writing to String cannot fail");
        self.output.push('\n');
    }

    fn indented(&mut self, callback: impl FnOnce(&mut Self)) {
        self.indent += 1;
        callback(self);
        self.indent -= 1;
    }

    fn finish(self) -> String {
        self.output
    }
}
