[default]
description = "Default permissions for the picker plugin."
permissions = [
  "allow-getHttpServerBase",
  "allow-pickFolder",
  "allow-pickImages",
  "allow-pickVideos",
  "allow-pickKgpgFile",
  "allow-openImage",
  "allow-openVideo",
  "allow-getImageThumbnail",
  "allow-computeHash",
  "allow-getMimeType",
  "allow-getDisplayName",
  "allow-getContentSize",
  "allow-getImageDimensions",
  "allow-getVideoDimensions",
  "allow-isDirectory",
  "allow-listContentChildren",
  "allow-readFileBytes",
  "allow-takePersistablePermission",
  "allow-copyImageToPictures",
  "allow-copyExtractedImagesToPictures",
]
