// 全局组件 / 指令的模板类型声明：`app.use(ElementPlus)` 在运行时全局注册了
// component.ts 里的全部组件，但 vue-tsc 只认 `GlobalComponents` 声明——缺了它，
// 模板里的 `<el-switch>` 等在类型上是 any，事件回调参数会报 TS7006 隐式 any。
// 对应上游 element-plus 包根的 global.d.ts（vendor 时漏掉）。
// 新增 / 删除 component.ts 里的组件时同步本文件。
declare module 'vue' {
  export interface GlobalComponents {
    ElAffix: typeof import('@kabegame/element-plus')['ElAffix']
    ElAlert: typeof import('@kabegame/element-plus')['ElAlert']
    ElAutocomplete: typeof import('@kabegame/element-plus')['ElAutocomplete']
    ElAutoResizer: typeof import('@kabegame/element-plus')['ElAutoResizer']
    ElAvatar: typeof import('@kabegame/element-plus')['ElAvatar']
    ElAvatarGroup: typeof import('@kabegame/element-plus')['ElAvatarGroup']
    ElBacktop: typeof import('@kabegame/element-plus')['ElBacktop']
    ElBadge: typeof import('@kabegame/element-plus')['ElBadge']
    ElBreadcrumb: typeof import('@kabegame/element-plus')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('@kabegame/element-plus')['ElBreadcrumbItem']
    ElButton: typeof import('@kabegame/element-plus')['ElButton']
    ElButtonGroup: typeof import('@kabegame/element-plus')['ElButtonGroup']
    ElCalendar: typeof import('@kabegame/element-plus')['ElCalendar']
    ElCard: typeof import('@kabegame/element-plus')['ElCard']
    ElCarousel: typeof import('@kabegame/element-plus')['ElCarousel']
    ElCarouselItem: typeof import('@kabegame/element-plus')['ElCarouselItem']
    ElCascader: typeof import('@kabegame/element-plus')['ElCascader']
    ElCascaderPanel: typeof import('@kabegame/element-plus')['ElCascaderPanel']
    ElCheckTag: typeof import('@kabegame/element-plus')['ElCheckTag']
    ElCheckbox: typeof import('@kabegame/element-plus')['ElCheckbox']
    ElCheckboxButton: typeof import('@kabegame/element-plus')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('@kabegame/element-plus')['ElCheckboxGroup']
    ElCol: typeof import('@kabegame/element-plus')['ElCol']
    ElCollapse: typeof import('@kabegame/element-plus')['ElCollapse']
    ElCollapseItem: typeof import('@kabegame/element-plus')['ElCollapseItem']
    ElCollapseTransition: typeof import('@kabegame/element-plus')['ElCollapseTransition']
    ElColorPickerPanel: typeof import('@kabegame/element-plus')['ElColorPickerPanel']
    ElColorPicker: typeof import('@kabegame/element-plus')['ElColorPicker']
    ElConfigProvider: typeof import('@kabegame/element-plus')['ElConfigProvider']
    ElContainer: typeof import('@kabegame/element-plus')['ElContainer']
    ElAside: typeof import('@kabegame/element-plus')['ElAside']
    ElFooter: typeof import('@kabegame/element-plus')['ElFooter']
    ElHeader: typeof import('@kabegame/element-plus')['ElHeader']
    ElMain: typeof import('@kabegame/element-plus')['ElMain']
    ElDatePicker: typeof import('@kabegame/element-plus')['ElDatePicker']
    ElDatePickerPanel: typeof import('@kabegame/element-plus')['ElDatePickerPanel']
    ElDescriptions: typeof import('@kabegame/element-plus')['ElDescriptions']
    ElDescriptionsItem: typeof import('@kabegame/element-plus')['ElDescriptionsItem']
    ElDialog: typeof import('@kabegame/element-plus')['ElDialog']
    ElDivider: typeof import('@kabegame/element-plus')['ElDivider']
    ElDrawer: typeof import('@kabegame/element-plus')['ElDrawer']
    ElDropdown: typeof import('@kabegame/element-plus')['ElDropdown']
    ElDropdownItem: typeof import('@kabegame/element-plus')['ElDropdownItem']
    ElDropdownMenu: typeof import('@kabegame/element-plus')['ElDropdownMenu']
    ElEmpty: typeof import('@kabegame/element-plus')['ElEmpty']
    ElForm: typeof import('@kabegame/element-plus')['ElForm']
    ElFormItem: typeof import('@kabegame/element-plus')['ElFormItem']
    ElIcon: typeof import('@kabegame/element-plus')['ElIcon']
    ElImage: typeof import('@kabegame/element-plus')['ElImage']
    ElImageViewer: typeof import('@kabegame/element-plus')['ElImageViewer']
    ElInput: typeof import('@kabegame/element-plus')['ElInput']
    ElInputNumber: typeof import('@kabegame/element-plus')['ElInputNumber']
    ElInputTag: typeof import('@kabegame/element-plus')['ElInputTag']
    ElInputOtp: typeof import('@kabegame/element-plus')['ElInputOtp']
    ElLink: typeof import('@kabegame/element-plus')['ElLink']
    ElMenu: typeof import('@kabegame/element-plus')['ElMenu']
    ElMenuItem: typeof import('@kabegame/element-plus')['ElMenuItem']
    ElMenuItemGroup: typeof import('@kabegame/element-plus')['ElMenuItemGroup']
    ElSubMenu: typeof import('@kabegame/element-plus')['ElSubMenu']
    ElPageHeader: typeof import('@kabegame/element-plus')['ElPageHeader']
    ElPagination: typeof import('@kabegame/element-plus')['ElPagination']
    ElPopconfirm: typeof import('@kabegame/element-plus')['ElPopconfirm']
    ElPopover: typeof import('@kabegame/element-plus')['ElPopover']
    ElPopper: typeof import('@kabegame/element-plus')['ElPopper']
    ElProgress: typeof import('@kabegame/element-plus')['ElProgress']
    ElRadio: typeof import('@kabegame/element-plus')['ElRadio']
    ElRadioButton: typeof import('@kabegame/element-plus')['ElRadioButton']
    ElRadioGroup: typeof import('@kabegame/element-plus')['ElRadioGroup']
    ElRate: typeof import('@kabegame/element-plus')['ElRate']
    ElResult: typeof import('@kabegame/element-plus')['ElResult']
    ElRow: typeof import('@kabegame/element-plus')['ElRow']
    ElScrollbar: typeof import('@kabegame/element-plus')['ElScrollbar']
    ElSelect: typeof import('@kabegame/element-plus')['ElSelect']
    ElOption: typeof import('@kabegame/element-plus')['ElOption']
    ElOptionGroup: typeof import('@kabegame/element-plus')['ElOptionGroup']
    ElSelectV2: typeof import('@kabegame/element-plus')['ElSelectV2']
    ElSkeleton: typeof import('@kabegame/element-plus')['ElSkeleton']
    ElSkeletonItem: typeof import('@kabegame/element-plus')['ElSkeletonItem']
    ElSlider: typeof import('@kabegame/element-plus')['ElSlider']
    ElSpace: typeof import('@kabegame/element-plus')['ElSpace']
    ElStatistic: typeof import('@kabegame/element-plus')['ElStatistic']
    ElCountdown: typeof import('@kabegame/element-plus')['ElCountdown']
    ElSteps: typeof import('@kabegame/element-plus')['ElSteps']
    ElStep: typeof import('@kabegame/element-plus')['ElStep']
    ElSwitch: typeof import('@kabegame/element-plus')['ElSwitch']
    ElTable: typeof import('@kabegame/element-plus')['ElTable']
    ElTableColumn: typeof import('@kabegame/element-plus')['ElTableColumn']
    ElTableV2: typeof import('@kabegame/element-plus')['ElTableV2']
    ElTag: typeof import('@kabegame/element-plus')['ElTag']
    ElText: typeof import('@kabegame/element-plus')['ElText']
    ElTimePicker: typeof import('@kabegame/element-plus')['ElTimePicker']
    ElTimeSelect: typeof import('@kabegame/element-plus')['ElTimeSelect']
    ElTimeline: typeof import('@kabegame/element-plus')['ElTimeline']
    ElTimelineItem: typeof import('@kabegame/element-plus')['ElTimelineItem']
    ElTooltip: typeof import('@kabegame/element-plus')['ElTooltip']
    ElTransfer: typeof import('@kabegame/element-plus')['ElTransfer']
    ElTree: typeof import('@kabegame/element-plus')['ElTree']
    ElTreeSelect: typeof import('@kabegame/element-plus')['ElTreeSelect']
    ElTreeV2: typeof import('@kabegame/element-plus')['ElTreeV2']
    ElUpload: typeof import('@kabegame/element-plus')['ElUpload']
    ElWatermark: typeof import('@kabegame/element-plus')['ElWatermark']
    ElTour: typeof import('@kabegame/element-plus')['ElTour']
    ElTourStep: typeof import('@kabegame/element-plus')['ElTourStep']
    ElAnchor: typeof import('@kabegame/element-plus')['ElAnchor']
    ElAnchorLink: typeof import('@kabegame/element-plus')['ElAnchorLink']
    ElSegmented: typeof import('@kabegame/element-plus')['ElSegmented']
    ElMention: typeof import('@kabegame/element-plus')['ElMention']
    ElSplitter: typeof import('@kabegame/element-plus')['ElSplitter']
    ElSplitterPanel: typeof import('@kabegame/element-plus')['ElSplitterPanel']
  }

  export interface GlobalDirectives {
    vLoading: typeof import('@kabegame/element-plus')['vLoading']
    vInfiniteScroll: typeof import('@kabegame/element-plus')['ElInfiniteScroll']
    vPopover: typeof import('@kabegame/element-plus')['ElPopoverDirective']
  }
}

export {}
