server {
    listen 80;
    listen [::]:80;
    server_name localhost-nginx-proxy-manager;
    access_log /data/logs/fallback_http_access.log standard;
    error_log /data/logs/fallback_http_error.log warn;
    location / {
        index index.html;
        root /var/www/html;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _;

    ssl_certificate /data/custom_ssl/npm-2/fullchain.pem;
    ssl_certificate_key /data/custom_ssl/npm-2/privkey.pem;
    include conf.d/include/ssl-ciphers.conf;

    ssl_session_timeout 5m;
    ssl_session_cache shared:SSL:20m;
    ssl_session_tickets off;

    access_log /data/logs/fallback_http_access.log standard;
    error_log /data/logs/fallback_http_error.log warn;

    return 444;
}