#![cfg(feature = "client-codegen")]

use pathql_rs::client_codegen::CodegenTarget;
use pathql_rs::{
    ClosureExecutor, EngineError, Namespace, Provider, ProviderDef, ProviderRegistry,
    ProviderRuntime, SimpleName, SqlDialect,
};
use std::collections::HashMap;
use std::sync::Arc;

struct StubProvider;

impl Provider for StubProvider {}

fn parse_def(raw: &str) -> ProviderDef {
    serde_json::from_str(raw).unwrap()
}

fn runtime() -> Arc<ProviderRuntime> {
    let mut registry = ProviderRegistry::new();
    registry
        .register(parse_def(
            r#"{
                "namespace": "test",
                "name": "gallery_route",
                "list": {
                    "all": { "provider": "all_provider" },
                    "fail-key": { "provider": "all_provider" },
                    "~weird": { "provider": "all_provider" },
                    "localImport": { "provider": "local_import_entry" },
                    "missing": { "provider": "missing_provider" },
                    "${row.name}": {
                        "sql": "SELECT name FROM items",
                        "data_var": "row",
                        "provider": "child_provider",
                        "alias": "plugin"
                    },
                    "${template.name}": {
                        "sql": "SELECT name, provider FROM items",
                        "data_var": "template",
                        "provider": "${template.provider}",
                        "alias": "templated"
                    },
                    "${extend.name}": {
                        "delegate": { "provider": "local_import_entry" },
                        "child_var": "extend",
                        "alias": "extension"
                    }
                },
                "resolve": {
                    "x[1-9][0-9]*x": {
                        "provider": "paginate",
                        "alias": "page_size"
                    },
                    "raw[0-9]+": { "provider": "paginate" },
                    ".*": {
                        "delegate": { "provider": "local_import_entry" },
                        "child_var": "extend",
                        "alias": "fallback"
                    }
                }
            }"#,
        ))
        .unwrap();

    for name in ["all_provider", "child_provider", "paginate"] {
        registry
            .register(parse_def(&format!(
                r#"{{"namespace":"test","name":"{name}"}}"#
            )))
            .unwrap();
    }

    // 两个 FQN 归一化后都得到 ABFooNode，按 FQN 字典序追加序号。
    registry
        .register(parse_def(r#"{"namespace":"a-b","name":"foo"}"#))
        .unwrap();
    registry
        .register(parse_def(r#"{"namespace":"a","name":"b_foo"}"#))
        .unwrap();
    registry
        .register(parse_def(
            r#"{"namespace":"plugins.pixiv-rank","name":"entry_provider"}"#,
        ))
        .unwrap();
    registry
        .register(parse_def(
            r#"{
                "namespace": "test",
                "name": "single_dynamic",
                "list": {
                    "${row.name}": {
                        "sql": "SELECT name FROM items",
                        "data_var": "row",
                        "provider": "child_provider"
                    }
                }
            }"#,
        ))
        .unwrap();

    registry
        .register_provider(
            Namespace("test".into()),
            SimpleName("local_import_entry".into()),
            |_| Ok(Arc::new(StubProvider) as Arc<dyn Provider>),
        )
        .unwrap();

    let executor = Arc::new(ClosureExecutor::new(SqlDialect::Sqlite, |_sql, _params| {
        Ok(Vec::new())
    }));
    let runtime = ProviderRuntime::with_registry(Arc::new(registry), executor, HashMap::new());
    runtime
        .register_schema("gallery", "images", "test", "gallery_route")
        .unwrap();
    runtime
        .register_schema("fail-images", "images", "test", "gallery_route")
        .unwrap();
    runtime
}

fn generate(runtime: &ProviderRuntime) -> Result<String, EngineError> {
    runtime.client_codegen(CodegenTarget::TypeScript)
}

#[test]
fn typescript_snapshot_contains_expected_runtime_types_and_edges() {
    let output = generate(&runtime()).unwrap();

    assert!(output.starts_with(
        "// AUTO-GENERATED by `kabegame-cli pathql generate` — DO NOT EDIT.\n// Target: TypeScript\n"
    ));
    assert!(output.contains(
        "const encodeSeg = (s: string) =>\n  encodeURIComponent(s.startsWith(\"~\") ? \"~\" + s : s);"
    ));
    assert!(output.contains("type AnyProviderNode = AnyProviderMethods & {"));

    assert!(output.contains("class TestGalleryRouteNode extends NodeBase"));
    assert!(output.contains("get all(): TestAllProviderNode"));
    assert!(output.contains("get [\"fail-key\"](): TestAllProviderNode"));
    assert!(output.contains("get [\"~weird\"](): TestAllProviderNode"));
    assert!(output.contains("return this._seg(\"~weird\", TestAllProviderNode);"));

    assert!(output.contains("$resolvePageSize(seg: string): TestPaginateNode"));
    assert!(!output.contains("$resolveRaw"));
    assert!(output.contains("$childPlugin(name: string): TestChildProviderNode"));
    assert!(output.contains("$childTemplated(name: string): TestGalleryRouteTemplateNode"));
    assert!(output.contains("$childExtension(name: string): TestGalleryRouteExtendNode"));
    assert!(output.contains("$resolveFallback(seg: string): TestGalleryRouteExtendNode"));

    assert!(output.contains("type OpaqueTestLocalImportEntryNode = AnyProviderNode;"));
    assert!(output.contains("type OpaqueTestMissingProviderNode = AnyProviderNode;"));
    assert!(output.contains("type TestGalleryRouteExtendNode = AnyProviderNode;"));
    assert!(output.contains("type TestGalleryRouteTemplateNode = AnyProviderNode;"));
    assert!(output.contains("get localImport(): OpaqueTestLocalImportEntryNode"));
    assert!(output.contains("get missing(): OpaqueTestMissingProviderNode"));

    assert!(output.contains("// DSL provider: a-b.foo\nclass ABFooNode extends NodeBase"));
    assert!(output.contains("// DSL provider: a.b_foo\nclass ABFooNode$2 extends NodeBase"));
    assert!(output.contains("class PluginsPixivRankEntryProviderNode extends NodeBase"));
    assert!(output.contains(
        "class TestSingleDynamicNode extends NodeBase {\n  $child(name: string): TestChildProviderNode"
    ));

    assert!(output.contains("gallery: new TestGalleryRouteNode([\"gallery://\"]),"));
    assert!(output.contains("\"fail-images\": new TestGalleryRouteNode([\"fail-images://\"]),"));
}

#[test]
fn generation_is_byte_for_byte_deterministic() {
    let runtime = runtime();
    let first = generate(&runtime).unwrap();
    let second = generate(&runtime).unwrap();
    assert_eq!(first, second);
}
