// Commands 模块
pub mod album;
#[cfg(not(target_os = "android"))]
pub mod crawler;
pub mod filesystem;
pub mod image;
pub mod misc;
pub mod plugin;
pub mod proxy;
pub mod settings;
#[cfg(not(target_os = "android"))]
pub mod surf;
pub mod task;
#[cfg(not(target_os = "android"))]
pub mod updater;
pub mod wallpaper;
pub mod window;

pub use album::*;
#[cfg(not(target_os = "android"))]
pub use crawler::*;
pub use filesystem::*;
pub use image::*;
pub use misc::*;
pub use plugin::*;
pub use proxy::*;
pub use settings::*;
#[cfg(not(target_os = "android"))]
pub use surf::*;
pub use task::*;
#[cfg(not(target_os = "android"))]
pub use updater::*;
pub use wallpaper::*;
pub use window::*;
