import '@kabegame/element-plus/components/base/style'
import '@kabegame/element-plus/theme-chalk/src/time-select.scss'
import '@kabegame/element-plus/components/scrollbar/style'
import '@kabegame/element-plus/components/popper/style'
import '@kabegame/element-plus/components/input/style'
import '@kabegame/element-plus/components/select/style'
